dict={}
name=input("enter name")
lang=input("enter lang")
dict.update({name:lang})
name=input("enter name")
lang=input("enter lang")
dict.update({name:lang})
name=input("enter name")
lang=input("enter lang")
dict.update({name:lang})
name=input("enter name")
lang=input("enter lang")
dict.update({name:lang})
print(dict)